#!/bin/bash
# Deploy a clone from template.
qm clone 9990 111 --name tst-svr-01

# Configure the SSH public key used for authentication, and configure the IP setup.
qm set 111 --ipconfig0 "ip=192.168.1.111/24,gw=192.168.1.1"
qm set 111 --nameserver="192.168.1.1 8.8.8.8"
qm set 111 --searchdomain="infra"
qm set 111 --sshkey ~/.ssh/id_rsa.pub
echo "Create VM: Complete!"
